version: "3.9"
services:
  mysql:
    image: mysql
    container_name: scapeRoomHQL2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "acuni"
    volumes:
      - ./scape.sql:/docker-entrypoint-initdb.d/scape.sql
